### ISSUE TITLE
Make sure the "EasyAdminExtensionBundle" bundle is correctly registered

### ISSUE THREAD

**Issue by vickyleon** [alterphp/EasyAdminMongoOdmBundle#3]
```
Unable to find file "@EasyAdminExtensionBundle/Controller/MongoOdmEasyAdminController.php" in 
@EasyAdminExtensionBundle/Controller/MongoOdmEasyAdminController.php (which is being imported from 
"/Applications/XAMPP/xamppfiles/htdocs/ebolution/014mx-ebolution-bot_ma-web-api/config/routes/easy_admin.yaml"). 
Make sure the "EasyAdminExtensionBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path 
"@EasyAdminExtensionBundle/Controller/MongoOdmEasyAdminController.php" is not empty.
```

Tengo un problema al intentar usar el bundle

**Comment by vickyleon** [comment]
archivo routes/easy_admin.yaml
```
easy_admin_mongo_odm_bundle: 
    resource: '@EasyAdminExtensionBundle/Controller/MongoOdmEasyAdminController.php'
    prefix: /admin/eao
    type: annotation
```

composer.json
```
"alterphp/easyadmin-mongo-odm-bundle": "dev-master",
 "easycorp/easyadmin-bundle": "^2",
"alterphp/easyadmin-extension-bundle": "^3.1",
```
